spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=CTT
    username: root
    password: root890624
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 150
      minimum-idle: 20
  freemarker:
    cache: false
    charset: utf-8
    content-type: text/html
    #    prefix: /templates
    suffix: .html
    template-loader-path: classpath:templates

# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true

  # 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true

  # dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_UR: /api/

  # dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

  # SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql
